name: merge

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

jobs:
  # Check if the PR has a title that matches the conventional commit format
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint and config-conventional
        run: npm install @commitlint/cli @commitlint/config-conventional
      - run: echo "${{ github.event.pull_request.title }}" | npx commitlint
