# See configuration examples by looking at the release.json and .manifest.json in the
# https://github.com/NEIAAC/typescript-template and https://github.com/NEIAAC/python-template repositories
# For actions like forcing a specific release version or working with multiple release
# branches, see the official documentation: https://github.com/googleapis/release-please
name: release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-24.04
    outputs:
      desktop: ${{ steps.metadata.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@58fbed0b875bc2f73d60680e175b4c152bf0eb39 # v4.2.0
        id: metadata
        with:
          config-file: release.json
          manifest-file: .manifest.json

  desktop:
    needs: [metadata]
    if: ${{ needs.metadata.outputs.desktop }}
    uses: ./.github/workflows/deploy.yaml
